### ISSUE TITLE
Goto endpoint/endpoint method definition

### ISSUE THREAD

**Issue by jsynowiec** [XVincentX/vscode-apielements#28]
Current symbol navigation is ok but more granular level would be great. I sometimes have 30+ endpoints each group (and a all standard HTTP methods for several of them). An ability to navigate to every "level", e.g. `Group Users -> Users Collection [/users] -> Fetch a collection [GET]` would be really helpful.

**Comment by XVincentX** [comment]
Hello,
this makes definitely sense and I think it's a general good idea.
I'll look into that and see if I can make it possible.

Actually I'm refactoring the way I'm traversing the AST in order to support Swagger and have more flexibility about what you consider a "symbol" (I'd like to make it configurable as not everybody think HTTP actions deserve to be a symbol). This might take a while but it's the second thing on my to-do list

**Comment by XVincentX** [comment]
I have just published version 0.3.0 which should fix the issue. I would really love if you could have a look into and let me know if it now makes sense to you!

@jsynowiec

**Comment by jsynowiec** [comment]
Great. Just updated. I'm currently working with a quite large specification (5k+ lines so far).

It works as expected. This is really a big help. Thanks! 

One idea though. Is it possible to add the HTTP method to each endpoint? Or change the symbol or symbol color for each HTTP method? I know that I can name then accordingly but displaying the method in square braces as a prefix to the endpoint name might be more useful.

E.g.

```
# Users Group
## User avatar
### Set user avatar [POST]
### Unset user avatar [DELETE]
```

Could be rendered as

```
Users
User avatar
[POST] Set user avatar - User avatar
[DELETE] Unset user avatar - User avatar
```

**Comment by XVincentX** [comment]
I think your idea makes definitely sense. Would you mind file a new issue with that so I can keep track of that?

Thanks a lot and - great that it's working well for you!

**Comment by jsynowiec** [comment]
#41
