### ISSUE TITLE
Problem with Blueprint validation

### ISSUE THREAD

**Issue by jsynowiec** [XVincentX/vscode-apielements#53]
After last updates, following MSON notation is reported as invalid:

```
+ position (object) - Last known position
    + latitude: 36.443662 (number, nullable)
        + Default: null
    + longitude: 28.227316 (number, nullable)
        + Default: null
```

<img width="687" alt="screenshot 2016-09-26 14 18 33" src="https://cloud.githubusercontent.com/assets/1029142/18834056/27520a26-83f4-11e6-9bce-02c4063c2e80.png">

Both, Apiary and Protagonist (Drafter?) reports this as a valid syntax. Moreover, I can't find anything in MSON spec that explains this.

**Comment by XVincentX** [comment]
Thanks a lot for the issue. I'll try to look into the parser and see if it's a known issue in current version and eventually update it!

**Comment by XVincentX** [comment]
@jsynowiec 

It seems like your issue is due to the parser update it has been provided with latest version.

Using string "null" as a default isn't supported.
Starting from 2.5.0, `nullable` means default null, so you should remove that line.

You should be able to find the change into drafter repo changelog if you're more interested into details.

**Comment by XVincentX** [comment]
https://github.com/apiaryio/drafter/blob/master/CHANGELOG.md#bug-fixes-1

**Comment by jsynowiec** [comment]
Ok, thanks. I'll update my blueprints and check if Apiary correctly shows values.
